---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: GoReleaser

on:
  workflow_call:
    inputs:
      snapshot:
        description: Build a snapshot instead of publishing a release
        type: boolean
        required: true

env:
  MISE_NO_HOOKS: "1"
  MISE_TASK_RUN_AUTO_INSTALL: "false"

jobs:
  goreleaser:
    name: GoReleaser
    runs-on: ubuntu-26.04
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Mise
        uses: jdx/mise-action@2d8d4cafcbd33be2ea37d2b6f5ad595363d1f1ca # v5.1.1
        with:
          cache: false
          experimental: true
          install_args: --locked go go:github.com/google/go-licenses/v2

      - name: Setup GoReleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          distribution: goreleaser
          version: "~> v2"
          install-only: true

      - name: Check GoReleaser configuration
        run: goreleaser check

      - name: Run GoReleaser
        run: goreleaser release --clean --parallelism=2 ${{ inputs.snapshot && '--snapshot' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
